## 1) Create Arrays

## Create a 1D, 2D, and 3D NumPy array.

In [2]:
import numpy as np

In [5]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
print(f"shape: {arr_1d.shape}")

[1 2 3 4 5]
shape: (5,)


In [6]:
# 2D array
arr_2d = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]])
print(arr_2d)
print(f"shape: {arr_2d.shape}")

[[1 2 3 4 5]
 [3 4 5 6 7]]
shape: (2, 5)


In [7]:
# 3D array
arr_3d = np.array([[[1,2,3,4,5], [2,3,4,5,6]],
                  [[9,8,7,6,5], [8,7,6,5,4]]])
print(arr_3d)
print(f"shape: {arr_3d.shape}")

[[[1 2 3 4 5]
  [2 3 4 5 6]]

 [[9 8 7 6 5]
  [8 7 6 5 4]]]
shape: (2, 2, 5)


## Create an array of zeros, ones, and random numbers.

In [16]:
## Array of zeros
np.zeros((5,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
# Array of ones
np.ones((5,8), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
# Array of random numbers
np.random(10, 51, (5,5))

array([[41, 25, 19, 19, 23],
       [22, 35, 16, 15, 10],
       [30, 19, 32, 35, 29],
       [47, 43, 40, 27, 22],
       [24, 26, 38, 14, 15]])

In [38]:
np.random.rand(2,4)

array([[0.62667138, 0.73122176, 0.43663628, 0.01775764],
       [0.00554295, 0.14229707, 0.36135125, 0.29136447]])

## Create an array with values from 10 to 50 (inclusive).

In [37]:
np.random.randint(10, 51, (5,6)).reshape(6,5)

array([[21, 22, 43, 14, 14],
       [46, 41, 35, 21, 37],
       [20, 43, 10, 36, 36],
       [35, 34, 22, 36, 13],
       [28, 44, 43, 18, 41],
       [14, 33, 25, 41, 36]])

# 2) Array Properties

## Print shape, size, and data type of an array.

In [42]:
my_arr = np.array([[1, 2, 3, 4, 5],
                  [5, 6, 7, 8, 9]])
arr_shape = my_arr.shape
arr_size = my_arr.size
arr_type = type(my_arr)

print(f"The shape of the array is: {arr_shape}")
print(f"The size of the array is: {arr_size}")
print(f"The type of the array is: {arr_type}")

The shape of the array is: (2, 5)
The size of the array is: 10
The type of the array is: <class 'numpy.ndarray'>


# Reshape a 1D array of size 12 into a 3×4 matrix.

In [45]:
my_arr = np.random.randint(10, 80, 12).reshape(3, 4)

In [46]:
my_arr

array([[44, 75, 20, 45],
       [21, 15, 39, 57],
       [55, 42, 45, 62]])

# 3) Indexing & Slicing

## Create a 3×3 matrix and extract:

## The second row

## The last column

## The element in row 2, column 3

In [47]:
my_arr = np.random.randint(10, 40, 9).reshape(3, 3)

In [49]:
my_arr

array([[15, 30, 15],
       [13, 12, 28],
       [14, 22, 37]])

In [48]:
## Second row

In [50]:
my_arr[1]

array([13, 12, 28])

In [51]:
my_arr[2]

array([14, 22, 37])

In [53]:
my_arr[1, 2]

28

# 4) Array Operations

## Add, subtract, multiply, and divide two arrays elementwise.

In [66]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([4, 5, 6, 7, 8])
add = arr_1 + arr_2
subtract = arr_1 - arr_2
multiply = arr_1 * arr_2
divide = arr_1 / arr_2
print(f"The add is: {add}")
print(f"The subtract is: {subtract}")
print(f"The multiply is: {multiply}")
print(f"The divide is: {divide}")

The add is: [ 5  7  9 11 13]
The subtract is: [-3 -3 -3 -3 -3]
The multiply is: [ 4 10 18 28 40]
The divide is: [0.25       0.4        0.5        0.57142857 0.625     ]


## Multiply a matrix by a scalar.

In [73]:
arr = np.array([[1, 2, 3],
            [4, 5, 6]])
scalar = 5
result = arr * scalar
print(f"The result is: {result}")

The result is: [[ 5 10 15]
 [20 25 30]]


## Square every element of an array.

In [80]:
arr = np.array([[1, 2, 3],
            [4, 5, 6]])
# result = np.square(arr) // Can be squared like this as well
result = arr ** 2
print(f"The result is: {result}")

The result is: [[ 1  4  9]
 [16 25 36]]
